.TH kumir2-bc 1 "" "" "Команды системы Кумир"
.SH ИМЯ
kumir2-bc \- компилятор программ на алгоритмическом языке "Кумир" в выполняемый байткод
.SH ОБЗОР
.B kumir2-bc 
[\-s] [\-g=<цел>] [\-e=<лит>] [\-o=<лит>] ПРОГРАММА.kum

.B kumir2-bc
[\-\-assembly] [\-\-debuglevel=<цел>] [\-\-encoding=<лит>] [\-\-out=<лит>] ПРОГРАММА.kum
.SH ОПИСАНИЕ
Данная команда преобразует текст программы на русском алгоритмическом языке в выполнимый системой "Кумир" байткод
.SH ОПЦИИ
.TP
.B \-\-assembly или \-s
если присутствует, то создает файл с текстовым представлением байткода (для отладки)
.TP
.BI \-g=<цел>\ или\ \-\-debuglevel=<цел>
устанавливает уровень отладочной информации при генерации байткода - значение от 0 (без отладочной информации) до 2 (вся возможная отладочная информация)
.TP
.BI \-e=<лит>\ или\ \-\-encoding=<лит>
явное указание кодировки текста входной программы
.TP
.BI \-o=<лит>\ или\ \-\-out=<лит>
имя выполняемого файла
.TP
.BI ПРОГРАММА.kum
имя файла исходного текста программы
.SH СМОТРИ ТАКЖЕ
.BR kumir2-llvmc (1)
.BR kumir2-run (1)
.BR kumir2-xrun (1)

