.TH kumir2-llvmc 1 "" "" "Команды системы Кумир"
.SH ИМЯ
kumir2-llvmc \- компилятор программ на алгоритмическом языке "Кумир" в выполняемый файл
.SH ОБЗОР
.B kumir2-llvmc 
[\-c] [\-S] [\-m] [\-l] [\-t] [\-v] [\-k] [\-g=<цел>] [\-e=<лит>] [\-o=<лит>] ПРОГРАММА.kum

.B kumir2-llvmc
[\-\-compile] [\-\-assembly] [\-\-main] [\-\-link] [\-\-stdlib] [\-\-verbose] [\-\-keep] [\-\-debuglevel=<цел>] [\-\-encoding=<лит>] [\-\-out=<лит>] ПРОГРАММА.kum
.SH ОПИСАНИЕ
Данная команда преобразует текст программы на русском алгоритмическом языке в выполнимый файл с использованием инструментария LLVM.
.SH ОПЦИИ
.TP
.B \-\-compile or \-c
если присутствует, то выполняется только компиляция файла в LLVM модуль, без создания выполняемого файла
.TP
.B \-\-assembly или \-S
если присутствует, то создает файл с текстовым представлением биткода LLVM (совместно с флагом \-c)
.TP
.B \-\-main or \-m
если присутствует, то созданный модуль содержит точку входа для выполнения (совместно с флагом \-c)
.TP
.B \-\-link or \-l
если присутствует, то в созданный модуль включается биткод из всех внешних исполнителей (совместно с флагом \-c)
.TP
.B \-\-stdlib or \-t
если присутствует, то в созданный модуль включается биткод стандартной библиотеки Кумир (совместно с флагом \-c)
.TP
.B \-\-verbose or \-v
если присутствует, то на терминал выводится результат работы внешних инструментов
.TP
.B \-\-keep or \-k
если присутствует, то созданные временные файлы, которые используются для передачи внешним инструментам, не удаляются
.TP
.BI \-g=<цел>\ или\ \-\-debuglevel=<цел>
устанавливает уровень отладочной информации при генерации байткода - значение от 0 (без отладочной информации) до 2 (вся возможная отладочная информация)
.TP
.BI \-e=<лит>\ или\ \-\-encoding=<лит>
явное указание кодировки текста входной программы
.TP
.BI \-o=<лит>\ или\ \-\-out=<лит>
имя выполняемого файла
.TP
.BI ПРОГРАММА.kum
имя файла исходного текста программы
.SH СМОТРИ ТАКЖЕ
.BR kumir2-bc (1)
.BR kumir2-run (1)
.BR kumir2-xrun (1)

