.TH kumir2-xrun 1 "" "" "Команды системы Кумир"
.SH ИМЯ
kumir2-xrun \- полнофункциональный выполнитель программ Кумир
.SH ОБЗОР
.B kumir2-xrun
[\-p|--pipe] [-t|--test] ФАЙЛ_БАЙТКОДА.kod [АРГ1 [АРГ2 ... [АРГn]]]
.SH ОПИСАНИЕ
Выполняет Кумир-байткод, который может использовать внешние исполнители
.SH ОПЦИИ
.TP
.B \-p\ или\ \-\-pipe
если присутствует, то неверный ввод приводит к ошибке выполнения, а не повторному запросу
.TP
.B \-t\ или\ \-\-test
запуск алгоритма @тестирование вместо главного
.TP
.BI ФАЙЛ_БАЙТКОДА.kod
имя выполняемого файла байткода
.TP
.BI [АРГ1\ [АРГ2\ ...\ [АРГn]]]
если присутствуют и первый алгоритм имеет параметры, то эти аргументы передаются первому алгоритму
.SH ЗАМЕЧАНИЯ
Как правило, нет необходимости явно вызывать данную команду, поскольку генерируемые .kod-файлы являются 
выполняемыми и содержат ссылку на утилиту kumir2-run в первой "строке" файла. При запуске программы интерпретатором kumir2-run, если требуется загрузка исполнителей, то ее выполнение передается интерпретатору kumir2-xrun

.SH СМОТРИ ТАКЖЕ
.BR kumir2-run (1)

