.TH kumir2-xrun 1 "" "" "Kumir utilities"
.SH NAME
kumir2-xrun \- full-feautered interpreter of portable Kumir bytecode
.SH SYNOPSIS
.B kumir2-xrun
[\-p|\-\-pipe] [-t|--test] BYTECODE_FILE.kod [ARG1 [ARG2 ... [ARGn]]]
.SH DESCRIPTION
Runs the Kumir bytecode using external modules
.SH OPTIONS
.TP
.B \-p\ or\ \-\-pipe
if present, then incorrect program input causes to runtime error but not trying it again 
.TP
.B \-t\ or\ \-\-test
use @тестирование algorithm as entry point instead of main
.TP
.BI BYTECODE_FILE.kod
executable bytecode file name
.TP
.BI [ARG1\ [ARG2\ ...\ [ARGn]]]
if present and first algorhitm has parameters, these arguments passed to first algorhitm
.SH NOTICE
Usually it is not required to explicitly run this command. Generated .kod-files are executable and contains link to kumir2-run binary at first "comment" line, then kumir2-run passes a program to kumir2-xrun if required

.SH SEE ALSO
.BR kumir2-run (1)

