.TH kumir2-run 1 "" "" "Kumir utilities"
.SH NAME
kumir2-run \- portable interpreter of portable Kumir bytecode
.SH SYNOPSIS
.B kumir2-run
[\-p] [-t|--test] BYTECODE_FILE.kod [ARG1 [ARG2 ... [ARGn]]]
.SH DESCRIPTION
Runs the Kumir bytecode with no external modules used
.SH OPTIONS
.TP
.B \-p
if present, then incorrect program input causes to runtime error but not trying it again 
.TP
.B \-t\ or\ \-\-test
use @тестирование algorithm as entry point instead of main
.TP
.BI BYTECODE_FILE.kod
executable bytecode file name
.TP
.BI [ARG1\ [ARG2\ ...\ [ARGn]]]
if present and first algorhitm has parameters, these arguments passed to first algorhitm
.SH NOTICE
Usually it is not required to explicitly run this command. Generated .kod-files are executable and
contains link to kumir2-run binary at first "comment" line

If program uses at least one external module, it passes to kumir2-xrun
.SH SEE ALSO
.BR kumir2-xrun (1)

